---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5
addons:
  chrome: stable

node_js: stable

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - export KARMA_SINGLE_RUN=true

before_script:
  - 'if [ "$KARMA_VERSION" ]; then yarn add karma@^$KARMA_VERSION; fi'

script:
  - xvfb-run yarn test

jobs:
  include:
    - stage: Latest (^1.x)

    - stage: Other Karma versions
      env: KARMA_VERSION=0.13
    -
      env: KARMA_VERSION=0.12
      node_js: 6
      before_script:
      - yarn remove karma karma-chrome-launcher karma-mocha
      - yarn add karma@^$KARMA_VERSION karma-chrome-launcher@0.2.0 karma-mocha@0.2.0;
    -
      node_js: 6
      env: KARMA_VERSION=0.11
      before_script:
      - yarn remove karma karma-chrome-launcher karma-mocha
      - yarn add karma@^$KARMA_VERSION karma-chrome-launcher@0.2.0 karma-mocha@0.2.0;
    -
      node_js: 4
      env: KARMA_VERSION=0.10
      before_script:
      - yarn remove karma karma-chrome-launcher karma-mocha
      - yarn add karma@^$KARMA_VERSION karma-chrome-launcher@0.1.0 karma-mocha@0.1.0;
    -
      node_js: 4
      env: KARMA_VERSION=0.9
      before_script:
      - yarn remove karma karma-chrome-launcher karma-mocha
      - yarn add karma@^$KARMA_VERSION karma-chrome-launcher@0.0.2 karma-mocha@0.1.0;
